### ISSUE TITLE
Add despeck module section to workflow.md

### ISSUE THREAD

**Issue by 4restwilliams** [isce-framework/fringe#23]
It would be helpful to add a section to workflows.md that details the usage of the despeck module. Also, in general what is your proposed use-case for despeck.py? Adaptive neighborhood despeckling could be useful for my analysis, but I am unsure of the optimal usage of despeck.py within the FRInGE workflow.

**Comment by piyushrpt** [comment]
Despeck is equivalent to a multilooking module, where the number of looks for each pixel is determined by its neighborhood. Its the atomic operation used for estimating the entries of the covariance / correlation matrix in EVD. Details can be found here:
https://github.com/isce-framework/fringe/blob/master/src/despeck/docs/README.md

It is meant to generate equivalent multilooked interferograms for SBAS like analysis or for generating cleaner amplitude maps. As such, it is incorporated into EVD and not necessarily used by itself in the workflow.

**Comment by hfattahi** [comment]
If the inout is one SLC, the despeck module, gives you a despeckled amplitude image of that SLC. Basically each pixel would be averaged to reduce noise. So you will get a nice looking despeckled amplitude image. Since the neighborhood map is used then Point like pixels (PS pixels) still stand out are not getting averaged with their neighbors because they are not similar to their neighbors. 
If the input to the module are two SLCs then the interferogram is generated and is multi-looked over the local neighborhood. So the result will be an adoptively multi-looked interferogram but not decimated. Sharp features and PS pixels are better preserved as the interferogram spacing remains at full resolution. By the time I got here, @piyushrpt already answered. But I still post it :).

**Comment by 4restwilliams** [comment]
I apologize for my late reply on this. Thank you for these answers, they were very helpful.
